### ISSUE TITLE
Upgrade Contigs databases to v9

### ISSUE THREAD

**Issue by ozcan** [merenlab/anviserver#3]
Unfortunately upgrade script requires project name so they need to be upgraded manually

**Comment by meren** [comment]
Sorry for the late response, Ozcan. We don't have many contigs db's, right? I think for this time we can use `--name "Contigs Database"` for all :)

**Comment by ozcan** [comment]
Actually yes we do not use contigs db name at the moment, I do not know why I thought like we should give actual names :)
